services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=${UTILISATEUR_BD}
      - MARIADB_PASSWORD=${MDP_BD}
      - MARIADB_DATABASE=${NOM_BD}
      - MARIADB_ROOT_PASSWORD=${MDP_ROOT}
    ports:
      - 3306:3306
    volumes:
      - /Users/clement.veurrier/INFO411/TD6/db_data:/var/lib/mysql
  monapache:
    image: maz0k/monapache
    volumes:
      - .:/var/www/html
    ports:
      - 2005:80
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8081:80
  monubuntu:
    image: sniipzouille/monubuntu