services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=info411_projet_roblox
      - MARIADB_ROOT_PASSWORD=admin+
    ports:
      - 3306:3306
    volumes:
      - /Users/clement.veurrier/INFO411/TD6/db_data:/var/lib/mysql
  monapache:
    image: sniipzouille/monapache
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
  monubuntu:
    image: sniipzouille/monubuntu