name: Deploy to Server
on:
            push:
                branches:
                  - main
            
jobs:
            deploy:
                name: Deploy to Server
                runs-on: ubuntu-latest
            
                steps:
                  - name: Setup SSH
                    uses: webfactory/ssh-agent@v0.5.4
                    with:
                      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
                  - name: SSH into Server and Deploy
                    run: |
                      ssh -o StrictHostKeyChecking=no debian@51.68.82.153 \
                      "cd ${{ secrets.WORKDIR }} && git pull"
